### ISSUE TITLE
Errors when using bi/magento cache:clean

### ISSUE THREAD

**Issue by rkhoury82** [litespeedtech/magento2-LiteSpeed_LiteMage#5]
Hi,

I can install and use the module all ok. But I noticed today that when I run 
php bin/magento cache:clean I get the following errors:

  [Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.

  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

As soon as I disable the module php bin/magento module:disable Litespeed_Litemage the errors go away.

server & software:
Litespeed Enterprise
PHP 7.0.10
MYSQL 5.7
Magento 2.0.10

**Comment by sureshp007** [comment]
Hi ,
I got the same issue when clear cache after  installation .  

[Magento\Framework\Exception\SessionException]
Area code not set: Area code must be set before starting a session.

[Magento\Framework\Exception\LocalizedException]
Area code is not set

On debug.log 

[2016-12-21 05:28:53] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"servers":["[object] (Zend\\Uri\\Http: /)"],"tagsPattern":".*"},"is_exception":false} [].

How can i fix this issue. 
Thnx

**Comment by litespeedtech** [comment]
Sorry for the delay. I've investigated and knew what caused the issue. This will require some bigger code changes. I'll try to get it resolved this year.

Lauren

**Comment by rkhoury82** [comment]
Hey Lauren, just so you know, the error occurs on both 2.0.x and 2.1.x - I upgraded to 2.1.3 and tried again just to make sure it wasn't version specific.
Rudi

**Comment by litespeedtech** [comment]
I know. Since LiteMage purge is through HTTP header, which is working fine on regular browser visit, but for command line trigger, it does not have those HTTP connections. I have to make separate handling for that case. While varnish does not have this issue, as every time it purge, it will create a new socket connection to send a purge request, does not matter if from HTTP or command line. So the purge on varnish is expensive. That's also LiteMage advantage, but I need to handle this case separately.

**Comment by navarr** [comment]
👍 This greatly effects our deployment process.

**Comment by litespeedtech** [comment]
I just pushed V2.0.2 to fix this issue as my new year's gift to you.
Lauren

**Comment by rkhoury82** [comment]
Confirmed working and fixed
